version: "3.9"
services:
  mongodb:
    image: mongo:3.6.23
    volumes:
      - type: volume
        source: .db-data
        target: /root.bitcoin
  bitcoin-node-0:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        rpcuser=alice
        rpcpassword=gUzyr0i3R2h5wW7R7LfZgRvV0Z7GxbIehWW562tqtFA
    volumes:
      - type: volume
        source: .bitcoin-0
        target: /root.bitcoin
    # ports:
    #   - "18555:18444"
  bitcoin-node-1:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        disablewallet=1
        addnode=bitpay-bitcoin-node-0-1:18444
    volumes:
      - type: volume
        source: .bitcoin-1
        target: /data
  bitcore-node:
    image: bitcore-node
    ports:
      - "3000:3000"
  bitcore-wallet-service:
    image: bitcore-wallet-service
    ports:
      - "3232:3232"
    tty: true
  bitcore-wallet:
    image: bitcore-wallet
    network_mode: host
    tty: true
volumes:
  .db-data:
  .bitcoin-0:
  .bitcoin-1:
