services:
  mongodb:
    image: mongo:3.6.23
    volumes:
      - type: volume
        source: .db-data
        target: /root.bitcoin
  bitcoin-node-0:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      HOME: /home/bitcoin
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        server=1
        rpcuser=alice
        rpcpassword=gUzyr0i3R2h5wW7R7LfZgRvV0Z7GxbIehWW562tqtFA
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0
        txindex=1
    volumes:
      - type: volume
        source: .bitcoin-0
        target: /root.bitcoin
  bitcoin-node-1:
    image: btcpayserver/bitcoin:24.0.1-1
    environment:
      HOME: /home/bitcoin
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        disablewallet=1
        rpcallowip=0.0.0.0/0
        rpcbind=0.0.0.0
        addnode=bitpay-bitcoin-node-0-1:18444
    volumes:
      - type: volume
        source: .bitcoin-1
        target: /data
  bitcore-node:
    image: bitcore-node
    ports:
      - "3000:3000"
    tty: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/BTC/regtest/block/tip"]
      interval: 5s
      timeout: 10s
      retries: 5
  bitcore-wallet-service:
    image: bitcore-wallet-service
    ports:
      - "3232:3232"
    depends_on:
      bitcore-node:
        condition: service_healthy
  wallet:
    image: zmscode/bitpay-copay
    ports:
      - "8100:8100"
volumes:
  .db-data:
  .bitcoin-0:
  .bitcoin-1:
